baseURL: "https://nighttime.coffee"
languageCode: "en-us"
title: "Coffee by Moonlight" 

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-WD2SY6RK53

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: "Coffee by Moonlight"
    description: "Writings and projects"
    keywords: [Blog, Projects, Long Form]
    author: "Matthew J. Harmon"
    images: ["/images"]
    #    DateFormat: "2015-01-21"
    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    assets:
        favicon: "https://nighttime.coffee/favicon.gif"
        favicon16x16: "https://nighttime.coffee/favicon-16x16.png"
        favicon32x32: "https://nighttime.coffee/favicon-32x32.png"
        apple_touch_icon: "https://nighttime.coffee/apple-touch-icon.png"

    label:
        text: "Home"
        icon: /favicon-228x228.png
        iconHeight: 50

    
    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "🌙 ☕ Welcome, Willkommen, Bienvenue, Welkom, Karibu, Haere Mai, Afio Mai, 欢迎, ברוך הבא, ようこそ" 
        Content: Welcome to my place online to store my thoughts and project progress.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/NightTimeC0FF33"
        - name: github
          url: "https://github.com/nighttime-coffee/nighttimecoffee"

    analytics:
        google:
            SiteVerificationTag: "G-NPX1PXK5KT"
        bing:
            SiteVerificationTag: "633D94030C3E09C16596C75E4FCDD216"
        yandex:
            SiteVerificationTag: "edf7924840d2b07f"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/nighttime-coffee/nighttimecoffee"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content" ,"long form"]
menu:
    main:
        - identifier: Thoughts
          name: Blog
          url: /blog/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: Projects
          name: Projects
          url: /projects/
          weight: 30
        - identifier: "Long Form"
          name: "Long Form"
          url: /long_form/
          wight: 31
        - identifier: biography
          name: MatthewJHarmon.com
          url: https://matthewjharmon.com
          weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
